---
name: test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      # - name: Run tests
      #   shell: bash
      #   run: |
      #     while IFS= read -r -d '' file
      #     do
      #       bash "$file"
      #     done < <(find . -name 'tests.sh' -print0)

      - name: Run day 10 tests
        run: bash day10/tests.sh